# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RxswiftExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxswiftExercise

    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'

  target 'RxswiftExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxswiftExerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
